package com.dd.entity;

import com.base.BaseModel;

@SuppressWarnings("serial")
public class UploadFile extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PB_FILE.FILE_NAME
     *
     * @mbggenerated
     */
    private String id;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PB_FILE.GROUP_NAME
     *
     * @mbggenerated
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PB_FILE.ACTUAL_NAME
     *
     * @mbggenerated
     */
    private String actualName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PB_FILE.FILE_NAME
     *
     * @return the value of PB_FILE.FILE_NAME
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PB_FILE.FILE_NAME
     *
     * @param fileName the value for PB_FILE.FILE_NAME
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PB_FILE.GROUP_NAME
     *
     * @return the value of PB_FILE.GROUP_NAME
     * @mbggenerated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PB_FILE.GROUP_NAME
     *
     * @param groupName the value for PB_FILE.GROUP_NAME
     * @mbggenerated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PB_FILE.ACTUAL_NAME
     *
     * @return the value of PB_FILE.ACTUAL_NAME
     * @mbggenerated
     */
    public String getActualName() {
        return actualName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PB_FILE.ACTUAL_NAME
     *
     * @param actualName the value for PB_FILE.ACTUAL_NAME
     * @mbggenerated
     */
    public void setActualName(String actualName) {
        this.actualName = actualName == null ? null : actualName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PB_FILE
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fileName=").append(fileName);
        sb.append(", groupName=").append(groupName);
        sb.append(", actualName=").append(actualName);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PB_FILE
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UploadFile other = (UploadFile) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getFileName() == null ? other.getFileName() == null : this.getFileName().equals(other.getFileName()))
                && (this.getGroupName() == null ? other.getGroupName() == null : this.getGroupName().equals(other.getGroupName()))
                && (this.getActualName() == null ? other.getActualName() == null : this.getActualName().equals(other.getActualName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PB_FILE
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getFileName() == null) ? 0 : getFileName().hashCode());
        result = prime * result + ((getGroupName() == null) ? 0 : getGroupName().hashCode());
        result = prime * result + ((getActualName() == null) ? 0 : getActualName().hashCode());
        return result;
    }
}